[project]
id = "example.com/pgsql-gos-concurrent"
version = "0.1.0"
gossamer-version = "^v0.55.3"

[dependencies]
# pgsql_gos = { git = "https://github.com/gossamer-lang/pgsql-gos", tag = "v0.1.1" }
pgsql_gos = { path = "../.." }
